[build]
  # Build command for the React app
  command = "cd client && npm run build"
  # Directory to publish (React build output)
  publish = "client/build"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy rules - Update with your Render backend URL
# Replace 'your-app-name' with your actual Render service name
[[redirects]]
  from = "/api/*"
  to = "https://your-app-name.onrender.com/api/:splat"
  status = 200
  force = true
