[build]
  # Build command for the React app - install deps first
  command = "cd client && npm install && npm run build"
  # Directory to publish (React build output)
  publish = "client/build"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# API proxy rules - Forward API calls to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://oss-health-bgrn.onrender.com/api/:splat"
  status = 200
  force = true

# Redirect all routes to index.html for React Router (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"    
  status = 200
